site_name: Documentation Example

theme:
  name: readthedocs

plugins:
  - search
  - notion:
      # Minimal configuration - you can build/serve without Notion config
      # Add parent_page_id and version when ready to deploy
      # parent_page_id: 0cc7d539-ec4f-48c0-bf89-8a8abd3abb1b
      # version: "1.0.1"
      deploy_on_build: false
