site_name: MkDocs Notion Example
site_description: Example site using MkDocs Notion Plugin

plugins:
  - notion:
      notion_token: your-notion-integration-token
      database_id: your-notion-database-id
      cache_dir: .notion_cache  # optional, defaults to .notion_cache

nav:
  - Home: index.md
  - About: about.md
